GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiam9rb0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcyNjExNzI2NSwiZXhwIjoxNzI2MjAzNjY1fQ.ifL81pyuo8NLriiYMngI38TnHduv7duKA8BLtWGjDCU

###
POST http://localhost:5000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWhtYWRAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI2MTI1NDQzLCJleHAiOjE3MjYyMTE4NDN9.maiLwhTUelIWeKZI9ZxZAXWh7hmhjIRXCMGR99kt9OU


###
GET http://localhost:5000/karyawanPage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiam9rb0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcyNjExNzI2NSwiZXhwIjoxNzI2MjAzNjY1fQ.ifL81pyuo8NLriiYMngI38TnHduv7duKA8BLtWGjDCU


###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email":"joko@gmail.com",
  "password": "123",
  "confirm_password": "123",
  "role": "user"
}

###
GET http://localhost:5000/token

